routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\VehicleController;
use App\Http\Controllers\WorkshopController;
use App\Http\Controllers\VehicleOwnerController;
use App\Http\Controllers\WorkshopOwnerController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\Auth\ChangePasswordController;
use App\Http\Controllers\Auth\SocialiteController;
use App\Http\Controllers\Auth\GoogleLoginController;
use App\Http\Controllers\MapController;
use App\Http\Controllers\UserController;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\ValidationException;
use Laravel\Socialite\Facades\Socialite;

Route::post('/sanctum/token', function (Request $request) {
    $request->validate([
        'email' => 'required|email',
        'password' => 'required',
        'device_name' => 'required',
    ]);

    $user = User::where('email', $request->email)->first();

    if (! $user || ! Hash::check($request->password, $user->password)) {
        throw ValidationException::withMessages([
            'email' => ['The provided credentials are incorrect.'],
        ]);
    }

    return $user->createToken($request->device_name)->plainTextToken;
});

Route::middleware('auth:sanctum')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::resource('/vehicles', VehicleController::class);
    Route::resource('/vehicle-owners', VehicleOwnerController::class);
    Route::resource('/workshop-owners', WorkshopOwnerController::class);
    Route::resource('/workshops', WorkshopController::class);
    Route::resource('/calendar', CalendarController::class);
    Route::resource('/services', ServiceController::class);
    Route::get('/vehicles/api/index', [VehicleController::class, 'index_api']);
    Route::get('/vehicle-owners/api/index', [VehicleOwnerController::class, 'index_api']);
    Route::get('/workshop-owners/api/index', [WorkshopOwnerController::class, 'index_api']);
    Route::get('/workshops/api/index', [WorkshopController::class, 'index_api']);
    Route::any('/calendar/api/index/{is_approved}', [CalendarController::class, 'index_api']);
    Route::get('/services/api/index', [ServiceController::class, 'index_api']);
    Route::post('/vehicles/media', [VehicleController::class, 'storeMedia'])->name('vehicles.storeMedia');
    Route::post('/generate-vehicle', [VehicleController::class, 'generateVehicle']);
    Route::get('/change-password', [ChangePasswordController::class, 'show_form'])->name('change.password.form');
    Route::put('/change-password', [ChangePasswordController::class, 'change'])->name('change.password');
    Route::any('/delete-my-data', function () {
        return "<center><h1>Your data have been deleted successfully.</h1></center>";
    });
    Route::any('/vehicle_list/pdf', [VehicleController::class, 'listVehiclesInPdf']);
    Route::get('/map', [MapController::class, 'index'])->name('map.index');
    Route::get('/users', [UserController::class, 'index'])->name('users.index');
    Route::get('/users/api/index', [UserController::class, 'index_api']);
});

require __DIR__.'/auth.php';
Route::any('/login-with-google', [SocialiteController::class, 'loginWithGoogle'])->name('login-with-google');
Route::any('/callback-from-google', [SocialiteController::class, 'callbackFromGoogle'])->name('callback-from-google');
Route::any('/login-with-facebook', [SocialiteController::class, 'loginWithFacebook'])->name('login-with-facebook');
Route::any('/callback-from-facebook', [SocialiteController::class, 'callbackFromFacebook'])->name('callback-from-facebook');
Route::any('/choose-user-type-save', [SocialiteController::class, 'storeUserType'])->name('choose-user-type-save');
Route::any('/choose-user-type-form', [SocialiteController::class, 'showChooseUserTypeForm']);

Route::fallback(function () {
    return 'Silence is golden';
});

app/Models/WorkshopOwner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class WorkshopOwner extends Model
{
    use HasFactory;
}

app/Http/Controllers/WorkshopOwnerController.php
<?php

namespace App\Http\Controllers;

use App\Models\WorkshopOwner;
use App\Models\VehicleOwner;
use App\Models\User;
use App\Models\Workshop;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Models\Vehicle;
use App\Http\Requests\StoreWorkshopOwnerRequest;
use App\Http\Requests\UpdateWorkshopOwnerRequest;
use Illuminate\Support\Facades\Auth;
use App\Repositories\UserRepository;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;
use Ulluminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;
use Illuminate\Database\Seeder;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Arr;

// use Illuminate\Validation\Validator;

class WorkshopOwnerController extends Controller
{
    private $userRepository;

    public function __construct()
    {
        $this->userRepository = new UserRepository();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Gate::authorize('index workshop owners');

        return view('workshop_owners.index');
    }

    public function index_api()
    {
        Gate::authorize('index workshop owners');
        $workshopOwners = $this->userRepository->getWorkshopOwners();
        return $workshopOwners;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Gate::authorize('create workshop owner');
        $formHeader = 'Add workshop owner';
        $formType = 'create';
        $route = route('workshop-owners.store');
        return view('workshop_owners.form', compact('formHeader', 'formType', 'route'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreWorkshopOwnerRequest $request)
    {
        Gate::authorize('store workshop owner');
        $workshop = new Workshop();

        $workshopOwner = new User();
        $workshopOwner->first_name = $request->first_name;

        $workshop->name = $workshopOwner->first_name."'s workshop";
        $workshop->save();

        $workshopOwner->last_name = $request->last_name;
        $workshopOwner->email = $request->email;
        $workshopOwner->address = $request->address;
        $workshopOwner->password = Hash::make($request->password);
        $workshopOwner->assignRole('workshop owner');
        $workshopOwner->workshop_id = $workshop->id;
        $workshopOwner->save();

        return view('workshop_owners.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function show(User $workshopOwner)
    {
        Gate::authorize('show workshop owner');
        $formHeader = 'View workshop owner';
        $formType = 'show';
        $disabled = 'disabled';
        $route = route('workshop-owners.index');

        return view('workshop_owners.form', compact('formHeader', 'formType', 'disabled', 'workshopOwner', 'route'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function edit(User $workshopOwner)
    {
        Gate::authorize('edit workshop owner');
        $formHeader = 'Edit workshop owner';
        $formType = 'edit';
        $route = route('workshop-owners.update', $workshopOwner);

        return view('workshop_owners.form', compact('formHeader', 'formType', 'route', 'workshopOwner'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateWorkshopOwnerRequest $request, User $workshopOwner)
    {
        $this->authorize('update workshop owner');
        $workshopOwner->first_name = $request->first_name;
        $workshopOwner->last_name = $request->last_name;
        $workshopOwner->email = $request->email;
        $workshopOwner->address = $request->address;
        if (!empty($request->password)) {
            $workshopOwner->password = Hash::make($request->password);
        }
        $workshopOwner->save();

        return redirect()->route('workshop-owners.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $workshopOwner)
    {
        Gate::authorize('destroy workshop owner');
        $workshopOwner->delete();
    }
}

resources/views/workshop_owners/datatables.blade.php
<table style="width:100%;border-radius:15px;background:white;" id="workshop_owners_index" class="dt-responsive order-column hover nowrap">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Workshop</th>
            <th>Email</th>
            <th>Registration Date</th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>

resources/views/workshop_owners/form.blade.php
@extends('layouts.app')

@section('content_header')
    <h1>
        {{ $formHeader }}
    </h1>
@stop

@section('content')
    @parent
    @push('css')
        <link rel='stylesheet' href='{{ asset('css/vehicles/form.css') }}'/>
    @endpush
    <div class='col-12 col-sm-7 col-md-6 col-lg-6 col-xl-4 m-auto'>
    <form spellcheck='false' id="workshop_owner_form" action="{{ $route??"" }}" method="POST" class="ui form" enctype="multipart/form-data">
      @csrf
      @if(@$formType == 'edit')
        @method('PUT')
      @endif

      @if($errors->any())
      <div class="ui form error">
        <div class="ui error message">
          <div class="header">Whoops! There were some problems with your form. </div>
          @foreach ($errors->all() as $ErrorMessage)
            <div>{{ $ErrorMessage }}</div>
          @endforeach
          <p></p>
        </div>
      </div>
      @endif

      <h4 class="ui dividing header"></h4>

        <div class="d-flex flex-column">

            <div class="field @error('first_name') error @enderror col-12 required">
            <label>First name</label>
            <input name="first_name" style="{{ !empty($disabled) ? 'pointer-events:none;' : '' }}" value="{{ old('first_name', $workshopOwner->first_name??'') }}" type="text" maxlength="30" placeholder="First name" class="">
            </div>

            <div class="field @error('last_name') error @enderror col-12 required">
              <label>Last name</label>
              <input name="last_name" style="{{ !empty($disabled) ? 'pointer-events:none;' : '' }}" value="{{ old('last_name') ?? $workshopOwner->last_name??'' }}" type="text" maxlength="30" placeholder="Last name" class="">
            </div>

            <div class="field @error('email') error @enderror col-12 required">
              <label>Email</label>
              <input name="email" style="{{ !empty($disabled) ? 'pointer-events:none;' : '' }}" value="{{ old('email') ?? $workshopOwner->email??'' }}" type="text" maxlength="30" placeholder="Email" class="">
            </div>

            <div class="field @error('address') error @enderror col-12 required">
              <label>Address</label>
              <input name="address" style="{{ !empty($disabled) ? 'pointer-events:none;' : '' }}" value="{{ old('address') ?? $workshopOwner->address??'' }}" type="text" maxlength="30" placeholder="Address" class="">
            </div>
            @if(@$formType != 'show')
            <div class="field @error('password') error @enderror col-12 required">
              <label>Password</label>
              <input type='password' name="password" style="{{ !empty($disabled) ? 'pointer-events:none;' : '' }}" value="{{ old('password')??'' }}" type="text" maxlength="30" placeholder="Password" class="">
            </div>

            <div class="field @error('password_confirmation') error @enderror col-12 required">
              <label>Password confirmation</label>
              <input type="password" name="password_confirmation" style="{{ !empty($disabled) ? 'pointer-events:none;' : '' }}" value="{{ old('password_confirmation')??'' }}" type="text" maxlength="30" placeholder="Password confirmation" class="">
            </div>
            @endif

        </div>

      <h4 class="ui dividing header"></h4>

      @if($formType == 'show')
        <a href="{{ $route??'' }}" >
            <div class="ui button">Back</div>
        </a>
      @else
        <button class="ui button" type="submit" tabindex="0">Save</button>
      @endif
      </button>
    </form>
    </div>

@push('js')
@endpush

@endsection

@push('js')
@endpush

resources/views/workshop_owners/index.blade.php
@extends('layouts.app')

@section('content_header')
    <h1>Workshop Owners</h1>
@stop

@section('content')
@parent
    @include('workshop_owners.datatables')
@endsection

@push('js')
    @include('workshop_owners.js')
@endpush

resources/views/workshop_owners/js.blade.php
<script src="/js/sweetalert2_vehicles.js"></script>
<script src="/js/notyf_toasts.js"></script>
<script src="/js/workshop_owners_datatables.js"></script>
<script>

$(document).ready(function() {
    @can('create workshop owner')
        $(".row > div.eight.wide.column:first-child").prepend("\
            <form action='{{ route('workshop-owners.create') }}' method='GET'>\
                <button class='ui medium olive basic button'><i class='fa fa-plus fa-fw'></i>&nbsp;Add</button>\
            </form>\
        ");
    @endcan
    $("#workshop_owners_index tbody").on('click', 'td.sorting_1.dtr-control', function(event){
        showCrudButtons();
    });
    $('#workshop_owners_index').on( 'draw.dt', function () {
        showCrudButtons();
    });
});

function deleteRow(element) {
    let id = element.getAttribute('data-id').substring(8);
    axios.post('/workshop-owners/' + id, {
        _method: 'DELETE'
    })
    .then(function (response) {
        $("#workshop_owners_index").DataTable().ajax.reload();
        notyfToast('Workshop owner deleted successfully ', 'success')
    })
    .catch(function (error) {
        notyfToast(error.response.data.message, 'error');
    });
}

function showCrudButtons(){
    @can('show workshop owner')
        $("a[id^=workshop_owner_show").show();
    @endcan
    @can('edit workshop owner')
        $("a[id^=workshop_owner_edit").show();
    @endcan
    @can('destroy workshop owner')
        $("button[id^=workshop_owner_destroy").show();
    @endcan
}

</script>