routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\VehicleController;
use App\Http\Controllers\WorkshopController;
use App\Http\Controllers\VehicleOwnerController;
use App\Http\Controllers\WorkshopOwnerController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\Auth\ChangePasswordController;
use App\Http\Controllers\Auth\SocialiteController;
use App\Http\Controllers\Auth\GoogleLoginController;
use App\Http\Controllers\MapController;
use App\Http\Controllers\UserController;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\ValidationException;
use Laravel\Socialite\Facades\Socialite;

Route::post('/sanctum/token', function (Request $request) {
    $request->validate([
        'email' => 'required|email',
        'password' => 'required',
        'device_name' => 'required',
    ]);

    $user = User::where('email', $request->email)->first();

    if (! $user || ! Hash::check($request->password, $user->password)) {
        throw ValidationException::withMessages([
            'email' => ['The provided credentials are incorrect.'],
        ]);
    }

    return $user->createToken($request->device_name)->plainTextToken;
});

Route::middleware('auth:sanctum')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::resource('/vehicles', VehicleController::class);
    Route::resource('/vehicle-owners', VehicleOwnerController::class);
    Route::resource('/workshop-owners', WorkshopOwnerController::class);
    Route::resource('/workshops', WorkshopController::class);
    Route::resource('/calendar', CalendarController::class);
    Route::resource('/services', ServiceController::class);
    Route::get('/vehicles/api/index', [VehicleController::class, 'index_api']);
    Route::get('/vehicle-owners/api/index', [VehicleOwnerController::class, 'index_api']);
    Route::get('/workshop-owners/api/index', [WorkshopOwnerController::class, 'index_api']);
    Route::get('/workshops/api/index', [WorkshopController::class, 'index_api']);
    Route::any('/calendar/api/index/{is_approved}', [CalendarController::class, 'index_api']);
    Route::get('/services/api/index', [ServiceController::class, 'index_api']);
    Route::post('/vehicles/media', [VehicleController::class, 'storeMedia'])->name('vehicles.storeMedia');
    Route::post('/generate-vehicle', [VehicleController::class, 'generateVehicle']);
    Route::get('/change-password', [ChangePasswordController::class, 'show_form'])->name('change.password.form');
    Route::put('/change-password', [ChangePasswordController::class, 'change'])->name('change.password');
    Route::any('/delete-my-data', function () {
        return "<center><h1>Your data have been deleted successfully.</h1></center>";
    });
    Route::any('/vehicle_list/pdf', [VehicleController::class, 'listVehiclesInPdf']);
    Route::get('/map', [MapController::class, 'index'])->name('map.index');
    Route::get('/users', [UserController::class, 'index'])->name('users.index');
    Route::get('/users/api/index', [UserController::class, 'index_api']);
});

require __DIR__.'/auth.php';
Route::any('/login-with-google', [SocialiteController::class, 'loginWithGoogle'])->name('login-with-google');
Route::any('/callback-from-google', [SocialiteController::class, 'callbackFromGoogle'])->name('callback-from-google');
Route::any('/login-with-facebook', [SocialiteController::class, 'loginWithFacebook'])->name('login-with-facebook');
Route::any('/callback-from-facebook', [SocialiteController::class, 'callbackFromFacebook'])->name('callback-from-facebook');
Route::any('/choose-user-type-save', [SocialiteController::class, 'storeUserType'])->name('choose-user-type-save');
Route::any('/choose-user-type-form', [SocialiteController::class, 'showChooseUserTypeForm']);

Route::fallback(function () {
    return 'Silence is golden';
});

app/Models/Workshop.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Service;

class Workshop extends Model
{
    use HasFactory;
    use SoftDeletes;

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'created_at' => 'datetime:Y-m-d H:i',
    ];

    protected $fillable = [
        'name',
    ];

    public function users()
    {
        $this->hasMany(User::class);
    }

    public function suppliers()
    {
        return $this->belongsToMany(Supplier::class);
    }

    public function vehicles()
    {
        return $this->belongsToMany(Vehicle::class);
    }

    public function services()
    {
        return $this->hasMany(Service::class);
    }
}

app/Http/Controllers/WorkshopController.php
<?php

namespace App\Http\Controllers;

use App\Models\VehicleOwner;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Models\Vehicle;
use App\Models\Workshop;
use App\Http\Requests\StoreWorkshopRequest;
use App\Http\Requests\UpdateWorkshopRequest;
use Illuminate\Support\Facades\Auth;
use App\Repositories\UserRepository;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;
use Ulluminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;
use Illuminate\Database\Seeder;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Arr;
use App\Services\StringGeneratorService;

class WorkshopController extends Controller
{
    private $userRepository;
    private $stringGeneratorService;

    public function __construct()
    {
        $this->userRepository = new UserRepository();
        $this->stringGeneratorService = new StringGeneratorService();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Gate::authorize('index workshops');

        return view('workshops.index');
    }

    public function index_api()
    {
        Gate::authorize('index workshops');
        $workshops = Workshop::all();

        return $workshops;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Gate::authorize('create workshop');
        $formHeader = 'Add workshop';
        $formType = 'create';
        $route = route('workshops.store');
        return view('workshops.form', compact('formHeader', 'formType', 'route'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreWorkshopRequest $request)
    {
        Gate::authorize('store workshop');
        $workshop = new Workshop();
        $workshop->name = $request->name;
        $workshop->place = $request->place;
        $workshop->street = $request->street;
        $workshop->longitude = $request->longitude;
        $workshop->latitude = $request->latitude;
        $workshop->save();

        $workshopOwner = new User();
        $workshopOwner->first_name = "F.N. of ".$workshop->name;
        $workshopOwner->last_name = "L.N. of ".$workshop->last_name;
        $workshopOwner->email = $this->stringGeneratorService->generate_string('abcd', 3).'@'.$this->stringGeneratorService->generate_string('efgh', 3).'.com';
        $workshopOwner->address = 'Address';
        $workshopOwner->password = Hash::make('password');
        $workshopOwner->assignRole('workshop owner');
        $workshopOwner->workshop_id = $workshop->id;
        $workshopOwner->save();

        return view('workshops.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function show(Workshop $workshop)
    {
        Gate::authorize('show workshop');
        $formHeader = 'View workshop';
        $formType = 'show';
        $disabled = 'disabled';
        $route = route('workshops.index');

        return view('workshops.form', compact('formHeader', 'formType', 'disabled', 'workshop', 'route'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function edit(Workshop $workshop)
    {
        Gate::authorize('edit workshop');
        $formHeader = 'Edit workshop';
        $formType = 'edit';
        $route = route('workshops.update', $workshop);

        return view('workshops.form', compact('formHeader', 'formType', 'route', 'workshop'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateWorkshopRequest $request, Workshop $workshop)
    {
        $this->authorize('update workshop');
        $workshop->name = $request->name;
        $workshop->place = $request->place;
        $workshop->street = $request->street;
        $workshop->longitude = $request->longitude;
        $workshop->latitude = $request->latitude;
        $workshop->save();

        return redirect()->route('workshops.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function destroy(Workshop $workshop)
    {
        Gate::authorize('destroy workshop');
        $workshop->delete();
    }
}

resources/views/workshops/datatables.blade.php
<table style="width:100%;border-radius:15px;background:white;" id="workshops_index" class="dt-responsive order-column hover nowrap">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Address</th>
            <th>Vehicle Owners</th>
            <th>Vehicles</th>
            <th>Suppliers</th>            
            <th>Registration Date</th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>

resources/views/workshops/form.blade.php
@extends('layouts.app')

@section('content_header')
    <h1>
        {{ $formHeader }}
    </h1>
@stop

@section('content')
    @parent
    @push('css')
        <link rel='stylesheet' href='{{ asset('css/vehicles/form.css') }}'/>
        <link href="https://api.mapbox.com/mapbox-gl-js/v2.9.2/mapbox-gl.css" rel="stylesheet">
        <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
    @endpush

<style>
.mapboxgl-ctrl-geocoder {
    min-width: 100%;
}
</style>

    <div class='col-12 col-sm-7 col-md-6 col-lg-6 col-xl-4 m-auto'>
    <form spellcheck='false' id="workshop_form" action="{{ $route??"" }}" method="POST" class="ui form" enctype="multipart/form-data">
      @csrf
      @if(@$formType == 'edit')
        @method('PUT')
      @endif

      @if($errors->any())
      <div class="ui form error">
        <div class="ui error message">
          <div class="header">Whoops! There were some problems with your form. </div>
          @foreach ($errors->all() as $ErrorMessage)
            <div>{{ $ErrorMessage }}</div>
          @endforeach
          <p></p>
        </div>
      </div>
      @endif

      <h4 class="ui dividing header"></h4>

        <div class="d-flex flex-column">

            <div class="field @error('name') error @enderror col-12 required">
            <label>Name</label>
            <input name="name" style="{{ !empty($disabled) ? 'pointer-events:none;' : '' }}" value="{{ old('name', $workshop->name??'') }}" type="text" maxlength="30" placeholder="Name" class="">
            </div>

            <input hidden id="place" name="place" />

            <div id='geocoder' class="field col-12 required">
                <label>City/Town</label>
            </div>

            <div class="field @error('longitude') error @enderror col-12 ">
              <label>Longitude</label>
              <input id="longitude" name="longitude" style="{{ !empty($disabled) ? 'pointer-events:none;' : '' }}" value="{{ old('longitude') ?? $workshop->longitude??'' }}" type="text" maxlength="50" placeholder="Longitude" class="">
            </div>
            <div class="field @error('latitude') error @enderror col-12 ">
              <label>Latitude</label>
              <input id="latitude" name="latitude" style="{{ !empty($disabled) ? 'pointer-events:none;' : '' }}" value="{{ old('latitude') ?? $workshop->latitude??'' }}" type="text" maxlength="50" placeholder="Latitude" class="">
            </div>
            <div class="field @error('street') error @enderror col-12 ">
              <label>Street</label>
              <input name="street" style="{{ !empty($disabled) ? 'pointer-events:none;' : '' }}" value="{{ old('street') ?? $workshop->street??'' }}" type="text" maxlength="50" placeholder="Street" class="">
            </div>

        </div>

      <h4 class="ui dividing header"></h4>

      @if($formType == 'show')
        <a href="{{ $route??'' }}" >
            <div class="ui button">Back</div>
        </a>
      @else
        <button class="ui button" type="submit" tabindex="0">Save</button>
      @endif
      </button>
    </form>
    </div>

@endsection

@push('js')
    @include('workshops.form_js')
@endpush

resources/views/workshops/form_js.blade.php
<script src="https://api.mapbox.com/mapbox-gl-js/v2.9.2/mapbox-gl.js"></script>
<script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.min.js"></script>

<script>

mapboxgl.accessToken = "{{ env('MAPBOX_KEY') }}";

const geocoder = new MapboxGeocoder({
accessToken: mapboxgl.accessToken,
types: 'country,region,place,postcode,locality,neighborhood'
});

geocoder.addTo('#geocoder');

$(document).ready(function(){
    @if(!empty($disabled))
    jQuery(".mapboxgl-ctrl-geocoder--input").addClass("no-pointer-events");
    @endif
    jQuery(".mapboxgl-ctrl-geocoder--input").val("{{ old('place') ?? $workshop->place??'' }}");
    $(".mapboxgl-ctrl-geocoder--input").on("change", function(){
        var place = $(".mapboxgl-ctrl-geocoder--input").val();
    });
    geocoder.on('result', (e) => {
        console.log(JSON.stringify(e.result, null, 2));
        $("#place").val(e.result.place_name);
        $("#longitude").val(e.result.center[0]);
        $("#latitude").val(e.result.center[1]);
    });
});
</script>

resources/views/workshops/index.blade.php
@extends('layouts.app')

@section('content_header')
    <h1>Workshops</h1>
@stop

@section('content')
@parent
    @include('workshops.datatables')
@endsection

@push('js')
    @include('workshops.js')
@endpush

resources/views/workshops/js.blade.php
<script src="/js/sweetalert2_vehicles.js"></script>
<script src="/js/notyf_toasts.js"></script>
<script src="/js/workshops_datatables.js"></script>
<script>

$(document).ready(function() {
    @can('create workshop')
        $(".row > div.eight.wide.column:first-child").prepend("\
            <form action='{{ route('workshops.create') }}' method='GET'>\
                <button class='ui medium olive basic button'><i class='fa fa-plus fa-fw'></i>&nbsp;Add</button>\
            </form>\
        ");
    @endcan
    $("#workshops_index tbody").on('click', 'td.sorting_1.dtr-control', function(event){
        showCrudButtons();
    });
    $('#workshops_index').on( 'draw.dt', function () {
        showCrudButtons();
    });
});

function deleteRow(element) {
    let id = element.getAttribute('data-id').substring(8);
    axios.post('/workshops/' + id, {
        _method: 'DELETE'
    })
    .then(function (response) {
        $("#workshops_index").DataTable().ajax.reload();
        notyfToast('Workshop deleted successfully ', 'success')
    })
    .catch(function (error) {
        notyfToast(error.response.data.message, 'error');
    });
}

function showCrudButtons(){
    @can('show workshop')
        $("a[id^=workshop_show").show();
    @endcan
    @can('edit workshop')
        $("a[id^=workshop_edit").show();
    @endcan
    @can('destroy workshop')
        $("button[id^=workshop_destroy").show();
    @endcan
}

</script>