routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\VehicleController;
use App\Http\Controllers\WorkshopController;
use App\Http\Controllers\VehicleOwnerController;
use App\Http\Controllers\WorkshopOwnerController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\Auth\ChangePasswordController;
use App\Http\Controllers\Auth\SocialiteController;
use App\Http\Controllers\Auth\GoogleLoginController;
use App\Http\Controllers\MapController;
use App\Http\Controllers\UserController;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\ValidationException;
use Laravel\Socialite\Facades\Socialite;

Route::post('/sanctum/token', function (Request $request) {
    $request->validate([
        'email' => 'required|email',
        'password' => 'required',
        'device_name' => 'required',
    ]);

    $user = User::where('email', $request->email)->first();

    if (! $user || ! Hash::check($request->password, $user->password)) {
        throw ValidationException::withMessages([
            'email' => ['The provided credentials are incorrect.'],
        ]);
    }

    return $user->createToken($request->device_name)->plainTextToken;
});

Route::middleware('auth:sanctum')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::resource('/vehicles', VehicleController::class);
    Route::resource('/vehicle-owners', VehicleOwnerController::class);
    Route::resource('/workshop-owners', WorkshopOwnerController::class);
    Route::resource('/workshops', WorkshopController::class);
    Route::resource('/calendar', CalendarController::class);
    Route::resource('/services', ServiceController::class);
    Route::get('/vehicles/api/index', [VehicleController::class, 'index_api']);
    Route::get('/vehicle-owners/api/index', [VehicleOwnerController::class, 'index_api']);
    Route::get('/workshop-owners/api/index', [WorkshopOwnerController::class, 'index_api']);
    Route::get('/workshops/api/index', [WorkshopController::class, 'index_api']);
    Route::any('/calendar/api/index/{is_approved}', [CalendarController::class, 'index_api']);
    Route::get('/services/api/index', [ServiceController::class, 'index_api']);
    Route::post('/vehicles/media', [VehicleController::class, 'storeMedia'])->name('vehicles.storeMedia');
    Route::post('/generate-vehicle', [VehicleController::class, 'generateVehicle']);
    Route::get('/change-password', [ChangePasswordController::class, 'show_form'])->name('change.password.form');
    Route::put('/change-password', [ChangePasswordController::class, 'change'])->name('change.password');
    Route::any('/delete-my-data', function () {
        return "<center><h1>Your data have been deleted successfully.</h1></center>";
    });
    Route::any('/vehicle_list/pdf', [VehicleController::class, 'listVehiclesInPdf']);
    Route::get('/map', [MapController::class, 'index'])->name('map.index');
    Route::get('/users', [UserController::class, 'index'])->name('users.index');
    Route::get('/users/api/index', [UserController::class, 'index_api']);
});

require __DIR__.'/auth.php';
Route::any('/login-with-google', [SocialiteController::class, 'loginWithGoogle'])->name('login-with-google');
Route::any('/callback-from-google', [SocialiteController::class, 'callbackFromGoogle'])->name('callback-from-google');
Route::any('/login-with-facebook', [SocialiteController::class, 'loginWithFacebook'])->name('login-with-facebook');
Route::any('/callback-from-facebook', [SocialiteController::class, 'callbackFromFacebook'])->name('callback-from-facebook');
Route::any('/choose-user-type-save', [SocialiteController::class, 'storeUserType'])->name('choose-user-type-save');
Route::any('/choose-user-type-form', [SocialiteController::class, 'showChooseUserTypeForm']);

Route::fallback(function () {
    return 'Silence is golden';
});

app/Http/Controllers/CalendarController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Vehicle;
use App\Models\Workshop;
use App\Models\User;
use App\Models\Service;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Auth;
use App\Repositories\UserRepository;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;
use Ulluminate\Support\Facades\File;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Arr;
use Illuminate\Auth\Access\Response;
use Illuminate\Support\Facades\Redirect;
use App\Http\Resources\ServiceResource;
use App\Repositories\VehicleRepository;
use App\Repositories\ServiceRepository;
use PDF;

class CalendarController extends Controller
{
    private $vehicleRepository;
    private $serviceRepository;

    public function __construct()
    {
        $this->vehicleRepository = new VehicleRepository();
        $this->serviceRepository = new ServiceRepository();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Gate::authorize('index services');
        if (Auth::user()->hasRole('vehicle owner')) {
            $ownVehicles = $this->vehicleRepository->getOwnVehicles();
            return view('calendar.index', ['ownVehicles' => $ownVehicles]);
        }
        return view('calendar.index', ['disabled' => 'disabled']);
    }

    public function index_api($isApproved)
    {
        Gate::authorize('index services');
        $currentUser = Auth::user();
        if ($currentUser->hasRole('super admin')) {
            $services = Service::all()->where('is_approved', $isApproved);
        }
        if ($currentUser->hasRole('vehicle owner')) {
            $services = $this->serviceRepository->getVehicleOwnerServices($currentUser)->where('is_approved', $isApproved);
        }
        if ($currentUser->hasRole('workshop owner')) {
            $services = $this->serviceRepository->getWorkshopOwnerServices($currentUser)->where('is_approved', $isApproved);
        }
        return ServiceResource::collection($services);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Gate::authorize('store service');
        $service  =  new Service();
        $service->title = $request->title;
        $service->description = $request->description;
        $service_day = $request->service_day;
        $service->service_day = $service_day;
        $service->start = $service_day." ".$request->start.":00:00";
        $service->end = $service_day." ".$request->end.":00:00";
        $service->vehicle_id = $request->vehicle_id;
        $vehicle  =  Vehicle::find($request->vehicle_id);
        $service->workshop_id = $vehicle->workshops()->firstOrFail()->id;
        $service->save();

        return redirect()->route('calendar.index');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Gate::authorize('update service');
        $service = Service::find($id);
        $service->is_approved = empty($request->isApproved) ? 0 : $request->isApproved;
        $service->save();
        return redirect()->route('calendar.index');
    }
}

resources/views/calendar/calendar.blade.php
<div id='calendar'></div>

@include('calendar.modal')

resources/views/calendar/css.blade.php
<link href='{{asset("css/fullcalendar/main.css")}}' rel='stylesheet' />

resources/views/calendar/form.blade.php
        <form id="add_service_form" class="ui form" method="POST" action="{{ route('calendar.store') }}">
        @csrf
          <div class="field">
            <label>Name</label>
            <input type="text" name="title" value='service name' placeholder="Name" class="{{ !empty($disabled) ? 'pointer-events-none' : '' }}">
          </div>
          <div class="field">
            <label>Description</label>
            <input value='description' type="text" name="description" placeholder="Description" class="{{ !empty($disabled) ? 'pointer-events-none' : '' }}">
          </div>
          @if(Auth::user()->hasRole(['super admin', 'workshop owner']))
          <div class="field">
            <label>Owner</label>
            <input value='owner' type="text" name="owner" placeholder="Owner" class="{{ !empty($disabled) ? 'pointer-events-none' : '' }}">
          </div>
          @endif
          <div class="field">
            <label>Start hour</label>
            <input value='11' type="text" name="start" placeholder="Start hour" class="{{ !empty($disabled) ? 'pointer-events-none' : '' }}">
          </div>
          <div class="field">
            <label>End hour</label>
            <input value='12' type="text" name="end" placeholder="End hour" class="{{ !empty($disabled) ? 'pointer-events-none' : '' }}">
          </div>
          <div class="field">
            <label>Vehicle</label>
            <select id ="vehicle_id" name="vehicle_id" class="ui fluid  dropdown  {{ !empty($disabled) ? 'pointer-events-none' : '' }}">
                @if(!empty($ownVehicles))
                    @foreach($ownVehicles as $ownVehicle)
                        <option value='{{ $ownVehicle->id }}'>
                            {{ $ownVehicle->make }}
                        </option>
                    @endforeach
                @endif
            </select>
          </div>
          <input hidden id="service_day" name="service_day" />
          <input hidden id="service_id" name="service_id" />
        </form>

resources/views/calendar/index.blade.php
@extends('layouts.app')

@push('css')
    @include('calendar.css')
@endpush

@section('content_header')
    <h1>Calendar</h1>
@stop

@section('content')
@parent
    @include('calendar.calendar')
@endsection

@push('js')
    @include('calendar.js')
@endpush

resources/views/calendar/js.blade.php
<script src='{{asset("js/fullcalendar/main.js")}}'></script>
<script src='{{asset("js/notyf_toasts.js")}}'></script>
<script>
document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');
    var calendar = new FullCalendar.Calendar(calendarEl, {
        initialView: 'dayGridMonth',
        @if(Auth::user()->hasRole(['super admin', 'workshop owner']))
        editable: true,
        @endif

        headerToolbar: {
            left: 'prev,next today',
            center: 'title',
            right: 'dayGridMonth,timeGridWeek,listWeek'
        },
        headerToolbar: {
            left: 'prev,next today',
            center: 'title',
            right: 'dayGridMonth,timeGridWeek,timeGridDay'
        },
        dateClick: function(info) {
            @if(Auth::user()->hasRole('vehicle owner'))
                showFormModal(info);
            @endif
        },
        eventClick: function(info) {
            info.el.style.borderColor = 'red';
            @if(Auth::user()->hasRole(['workshop owner', 'super admin']))
                showFormModal(info);
            @endif

        },
        height: 655,
        eventSources: [
          {
            url: '/calendar/api/index/0',
            method: 'GET',
            extraParams: {
              custom_param1: 'something',
              custom_param2: 'somethingelse'
            },
            failure: function() {
              console.log('there was an error while fetching events!');
            },
            color: 'yellow',
            backgroundColor: 'yellow',

        },
          {
            url: '/calendar/api/index/1',
            method: 'GET',
            failure: function() {
              console.log('there was an error while fetching events!');
            },
            color: 'green',
            backgroundColor: 'green',

        },
          {
            url: '/calendar/api/index/2',
            method: 'GET',
            failure: function() {
              console.log('there was an error while fetching events!');
            },
            color: 'red',
            textColor: 'white',
            backgroundColor: 'red',
            eventColor: 'red',
          }

      ],
    });
    calendar.render();
    $('.ui.dropdown').dropdown();

    $('#add_service_modal').on('click', function (e) {
        e.stopPropagation();
    });
    $("#add_service_form_save_button").on('click', function(){
        $("#add_service_form").submit();
        $('#add_service_modal').modal('hide');
    });
    $("#add_service_form_cancel_button, #modal_close_button").on('click', function(){
        $('#add_service_modal').modal('hide');
    });
    $("#add_service_form_approve_button").on('click', function(){
        location.reload();
        approveOrDeclineService(true);
        $('#add_service_modal').modal('hide');
    });
    $("#add_service_form_decline_button").on('click', function(){
        location.reload();
        approveOrDeclineService(2);
        $('#add_service_modal').modal('hide');
    });
});

function showFormModal(info){

    $("#add_service_modal").modal('show');
    setServiceDay(info.dateStr);
    @if(Auth::user()->hasRole(['super admin', 'workshop owner']))
    setServiceId(info.event.id);
    setVehicleMake(info.event.extendedProps.make);
    setVehicleOwner(info.event.extendedProps.owner);
    setServiceTitle(info.event.title);
    setServiceDescription(info.event.extendedProps.description);
    setServiceStart(info.event.startStr);
    setServiceEnd(info.event.endStr);
    @endif
}
function setServiceDay(date){
    $('#service_day').val(date);
}
function setServiceId(id){
    $('#service_id').val(id);
}
function setServiceTitle(title){
    $( "input[name='title']" ).val(title);
}
function setServiceDescription(description){
    $("input[name='description']").val(description);
}
function setServiceStart(start){
    $("input[name='start']").val(start.substring(11,16));
}
function setServiceEnd(end){
    $("input[name='end']").val(end.substring(11,16));
}
function setVehicleMake(vehicle){
    $("#vehicle_id").append(new Option(vehicle, vehicle.id));
}
function setVehicleOwner(owner){
    $("input[name='owner']").val(owner);
}
function approveOrDeclineService(isApproved){
    serviceId = $("#service_id").val();
    axios.post('/calendar/' + serviceId, {
        _method: 'PUT',
        serviceId: serviceId,
        isApproved: isApproved,
    })
    .then(function (response) {
      notyfToast('Your decision has been saved', 'success');
    })
    .catch(function (error) {
        notyfToast(error.response.data.message, 'error');
    });


}

</script>

resources/views/calendar/modal.blade.php
<!-- Request a new service modal -->
<div id="add_service_modal" class="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Request a new service</h5>
        <button id="modal_close_button" type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

@include('calendar.form')

      </div>
      <div class="modal-footer">
          <button id="add_service_form_cancel_button" type="button" class="ui button" data-dismiss="modal">Cancel</button>
          @if(Auth::user()->hasRole('vehicle owner'))
          <button id="add_service_form_save_button" type="button" class="ui secondary button" data-dismiss="modal">Save</button>
          @endif
          @if(Auth::user()->hasRole(['super admin', 'workshop owner']))
          <button id="add_service_form_decline_button" type="button" class="ui button" data-dismiss="modal"><span class="text-danger">Decline</span></button>
          <button id="add_service_form_approve_button" type="button" class="ui button" data-dismiss="modal"><span class="text-success">Approve</span></button>
          @endif
      </div>
    </div>
  </div>
</div>