routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\VehicleController;
use App\Http\Controllers\WorkshopController;
use App\Http\Controllers\VehicleOwnerController;
use App\Http\Controllers\WorkshopOwnerController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\Auth\ChangePasswordController;
use App\Http\Controllers\Auth\SocialiteController;
use App\Http\Controllers\Auth\GoogleLoginController;
use App\Http\Controllers\MapController;
use App\Http\Controllers\UserController;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\ValidationException;
use Laravel\Socialite\Facades\Socialite;

Route::post('/sanctum/token', function (Request $request) {
    $request->validate([
        'email' => 'required|email',
        'password' => 'required',
        'device_name' => 'required',
    ]);

    $user = User::where('email', $request->email)->first();

    if (! $user || ! Hash::check($request->password, $user->password)) {
        throw ValidationException::withMessages([
            'email' => ['The provided credentials are incorrect.'],
        ]);
    }

    return $user->createToken($request->device_name)->plainTextToken;
});

Route::middleware('auth:sanctum')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::resource('/vehicles', VehicleController::class);
    Route::resource('/vehicle-owners', VehicleOwnerController::class);
    Route::resource('/workshop-owners', WorkshopOwnerController::class);
    Route::resource('/workshops', WorkshopController::class);
    Route::resource('/calendar', CalendarController::class);
    Route::resource('/services', ServiceController::class);
    Route::get('/vehicles/api/index', [VehicleController::class, 'index_api']);
    Route::get('/vehicle-owners/api/index', [VehicleOwnerController::class, 'index_api']);
    Route::get('/workshop-owners/api/index', [WorkshopOwnerController::class, 'index_api']);
    Route::get('/workshops/api/index', [WorkshopController::class, 'index_api']);
    Route::any('/calendar/api/index/{is_approved}', [CalendarController::class, 'index_api']);
    Route::get('/services/api/index', [ServiceController::class, 'index_api']);
    Route::post('/vehicles/media', [VehicleController::class, 'storeMedia'])->name('vehicles.storeMedia');
    Route::post('/generate-vehicle', [VehicleController::class, 'generateVehicle']);
    Route::get('/change-password', [ChangePasswordController::class, 'show_form'])->name('change.password.form');
    Route::put('/change-password', [ChangePasswordController::class, 'change'])->name('change.password');
    Route::any('/delete-my-data', function () {
        return "<center><h1>Your data have been deleted successfully.</h1></center>";
    });
    Route::any('/vehicle_list/pdf', [VehicleController::class, 'listVehiclesInPdf']);
    Route::get('/map', [MapController::class, 'index'])->name('map.index');
    Route::get('/users', [UserController::class, 'index'])->name('users.index');
    Route::get('/users/api/index', [UserController::class, 'index_api']);
});

require __DIR__.'/auth.php';
Route::any('/login-with-google', [SocialiteController::class, 'loginWithGoogle'])->name('login-with-google');
Route::any('/callback-from-google', [SocialiteController::class, 'callbackFromGoogle'])->name('callback-from-google');
Route::any('/login-with-facebook', [SocialiteController::class, 'loginWithFacebook'])->name('login-with-facebook');
Route::any('/callback-from-facebook', [SocialiteController::class, 'callbackFromFacebook'])->name('callback-from-facebook');
Route::any('/choose-user-type-save', [SocialiteController::class, 'storeUserType'])->name('choose-user-type-save');
Route::any('/choose-user-type-form', [SocialiteController::class, 'showChooseUserTypeForm']);

Route::fallback(function () {
    return 'Silence is golden';
});

app/Models/VehicleOwner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class VehicleOwner extends Model
{
    use HasFactory;
}

app/Http/Controllers/VehicleOwnerController.php
<?php

namespace App\Http\Controllers;

use App\Models\VehicleOwner;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Models\Vehicle;
use App\Http\Requests\StoreVehicleOwnerRequest;
use App\Http\Requests\UpdateVehicleRequest;
use App\Http\Requests\UpdateVehicleOwnerRequest;
use Illuminate\Support\Facades\Auth;
use App\Repositories\UserRepository;
use App\Services\VinGeneratorService;
use App\Services\VehicleGeneratorService;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;
use Ulluminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;
use Illuminate\Database\Seeder;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Arr;

class VehicleOwnerController extends Controller
{
    private $userRepository;
    private $vinGeneratorService;
    private $vehicleGeneratorService;

    public function __construct()
    {
        $this->userRepository = new UserRepository();
        $this->vinGeneratorService = new VinGeneratorService();
        $this->vehicleGeneratorService = new VehicleGeneratorService();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Gate::authorize('index vehicle owners');
        return view('vehicle_owners.index');
    }

    public function index_api()
    {
        Gate::authorize('index vehicle owners');
        if (Auth::user()->hasRole('super admin')) {
            $vehicleOwners = $this->userRepository->getVehicleOwners();
        }
        if (Auth::user()->hasRole('workshop owner')) {
            $currentUserWorkshop = Auth::user()->workshop()->firstOrFail();
            $workshopVehicles = $currentUserWorkshop->vehicles()->get();
            $vehicleOwners = collect();
            foreach ($workshopVehicles as $workshopVehicle) {
                $vehicleOwners = $vehicleOwners->concat($workshopVehicle->users()->get()->whereNotIn('id', $vehicleOwners->pluck('id'))); //prevents duplicates
            }
        }
        return $vehicleOwners;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Gate::authorize('create vehicle owner');
        $formHeader = 'Add vehicle owner';
        $formType = 'create';
        $route = route('vehicle-owners.store');

        return view('vehicle_owners.form', compact('formHeader', 'formType', 'route'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreVehicleOwnerRequest $request)
    {
        Gate::authorize('store vehicle owner');
        $vehicleOwner = new User();
        $vehicleOwner->first_name = $request->first_name;
        $vehicleOwner->last_name = $request->last_name;
        $vehicleOwner->email = $request->email;
        $vehicleOwner->address = $request->address;
        $vehicleOwner->password = Hash::make($request->password);
        $vehicleOwner->save();
        $vehicleOwner->assignRole('vehicle owner');

        return redirect()->route('vehicle-owners.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function show(User $vehicleOwner)
    {
        Gate::authorize('show vehicle owner');
        $formHeader = 'View vehicle owner';
        $formType = 'show';
        $disabled = 'disabled';
        $route = route('vehicle-owners.index');

        return view('vehicle_owners.form', compact('formHeader', 'formType', 'disabled', 'vehicleOwner', 'route'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function edit(User $vehicleOwner)
    {
        Gate::authorize('edit vehicle owner');
        $formHeader = 'Edit vehicle owner';
        $formType = 'edit';
        $route = route('vehicle-owners.update', $vehicleOwner);

        return view('vehicle_owners.form', compact('formHeader', 'formType', 'route', 'vehicleOwner'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateVehicleOwnerRequest $request, User $vehicleOwner)
    {
        $this->authorize('update vehicle owner');
        $vehicleOwner->first_name = $request->first_name;
        $vehicleOwner->last_name = $request->last_name;
        $vehicleOwner->email = $request->email;
        $vehicleOwner->address = $request->address;
        if (!empty($request->password)) {
            $vehicleOwner->password = Hash::make($request->password);
        }
        $vehicleOwner->save();

        return redirect()->route('vehicle-owners.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $vehicleOwner)
    {
        Gate::authorize('destroy vehicle owner');
        $this->authorize('delete', $vehicleOwner);
        $loggedInUser = Auth::user();
        if ($loggedInUser->hasRole('workshop owner')) {
            $workshopId = $loggedInUser->workshop_id;
            $workshopVehiclesIds = $loggedInUser->workshop()->firstOrFail()->vehicles()->get()->pluck('id');
            $vehiclesOfVehicleOwnerToDelete = $vehicleOwner->vehicles()->get();
            foreach ($vehiclesOfVehicleOwnerToDelete as $vehicleOfVehicleOwnerToDelete) {
                if ($workshopVehiclesIds->contains($vehicleOfVehicleOwnerToDelete->id)) {
                    $vehicleOfVehicleOwnerToDelete->workshops()->sync([7]);
                }// inserts workshop named 'none' into intermediate table "vehicle workshop"
            }
        } else {
            //super admin
            $vehiclesToDelete = $vehicleOwner->vehicles()->get();
            $vehicleOwner->delete();
            foreach ($vehiclesToDelete as $vehicleToDelete) {
                $vehicleToDelete->delete();
            }
        }
    }

    public function generateVehicle()
    {
        return $generatedVehicle = $this->vehicleGeneratorService->vehicleGeneratorService();
    }
}

resources/views/vehicle_owners/datatables.blade.php
<table style="width:100%;border-radius:15px;background:white;" id="vehicle_owners_index" class="dt-responsive order-column hover nowrap">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Vehicles</th>
            <th>Email</th>
            <th>Registration Date</th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>

resources/views/vehicle_owners/form.blade.php
@extends('layouts.app')

@section('content_header')
    <h1>
        {{ $formHeader }}
    </h1>
@stop

@section('content')
    @parent
    @push('css')
        <link rel='stylesheet' href='{{ asset('css/vehicles/form.css') }}'/>
    @endpush
    <div class='col-12 col-sm-7 col-md-6 col-lg-6 col-xl-4 m-auto'>
    <form spellcheck='false' id="vehicle_owner_form" action="{{ $route??"" }}" method="POST" class="ui form" enctype="multipart/form-data">
      @csrf
      @if(@$formType == 'edit')
        @method('PUT')
      @endif

      @if($errors->any())
      <div class="ui form error">
        <div class="ui error message">
          <div class="header">Whoops! There were some problems with your form. </div>
          @foreach ($errors->all() as $ErrorMessage)
            <div>{{ $ErrorMessage }}</div>
          @endforeach
          <p></p>
        </div>
      </div>
      @endif

      <h4 class="ui dividing header"></h4>

        <div class="d-flex flex-column">

            <div class="field @error('first_name') error @enderror col-12 required">
            <label>First name</label>
            <input name="first_name" style="{{ !empty($disabled) ? 'pointer-events:none;' : '' }}" value="{{ old('first_name', $vehicleOwner->first_name??'') }}" type="text" maxlength="30" placeholder="First name" class="">
            </div>

            <div class="field @error('last_name') error @enderror col-12 required">
              <label>Last name</label>
              <input name="last_name" style="{{ !empty($disabled) ? 'pointer-events:none;' : '' }}" value="{{ old('last_name') ?? $vehicleOwner->last_name??'' }}" type="text" maxlength="30" placeholder="Last name" class="">
            </div>

            <div class="field @error('email') error @enderror col-12 required">
              <label>Email</label>
              <input name="email" style="{{ !empty($disabled) ? 'pointer-events:none;' : '' }}" value="{{ old('email') ?? $vehicleOwner->email??'' }}" type="text" maxlength="30" placeholder="Email" class="">
            </div>

            <div class="field @error('address') error @enderror col-12 required">
              <label>Address</label>
              <input name="address" style="{{ !empty($disabled) ? 'pointer-events:none;' : '' }}" value="{{ old('address') ?? $vehicleOwner->address??'' }}" type="text" maxlength="30" placeholder="Address" class="">
            </div>
            @if(@$formType != 'show')
            <div class="field @error('password') error @enderror col-12 required">
              <label>Password</label>
              <input type='password' name="password" style="{{ !empty($disabled) ? 'pointer-events:none;' : '' }}" value="{{ old('password')??'' }}" type="text" maxlength="30" placeholder="Password" class="">
            </div>

            <div class="field @error('password_confirmation') error @enderror col-12 required">
              <label>Password confirmation</label>
              <input type="password" name="password_confirmation" style="{{ !empty($disabled) ? 'pointer-events:none;' : '' }}" value="{{ old('password_confirmation')??'' }}" type="text" maxlength="30" placeholder="Password confirmation" class="">
            </div>
            @endif


        </div>

      <h4 class="ui dividing header"></h4>

      @if($formType == 'show')
        <a href="{{ $route??'' }}" >
            <div class="ui button">Back</div>
        </a>
      @else
        <button class="ui button" type="submit" tabindex="0">Save</button>
      @endif
      </button>
    </form>
    </div>

@push('js')
@endpush

@endsection

@push('js')
@endpush

resources/views/vehicle_owners/index.blade.php
@extends('layouts.app')

@section('content_header')
    <h1>Vehicle Owners</h1>
@stop

@section('content')
@parent
    @include('vehicle_owners.datatables')
@endsection

@push('js')
    @include('vehicle_owners.js')
@endpush

resources/views/vehicle_owners/js.blade.php
<script src="/js/sweetalert2_vehicles.js"></script>
<script src="/js/notyf_toasts.js"></script>
<script src="/js/vehicle_owners_datatables.js"></script>
<script>
$(document).ready(function() {
    @can('create vehicle owner')
        $(".row > div.eight.wide.column:first-child").prepend("\
            <form action='{{ route('vehicle-owners.create') }}' method='GET'>\
                <button class='ui medium olive basic button'><i class='fa fa-plus fa-fw'></i>&nbsp;Add</button>\
            </form>\
        ");
    @endcan
    $("#vehicle_owners_index tbody").on('click', 'td.sorting_1.dtr-control', function(event){
        showCrudButtons();
    });
    $('#vehicle_owners_index').on( 'draw.dt', function () {
        showCrudButtons();
    });
});


function deleteRow(element) {
    let id = element.getAttribute('data-id').substring(8);
    axios.post('/vehicle-owners/' + id, {
        _method: 'DELETE'
    })
    .then(function (response) {
        $("#vehicle_owners_index").DataTable().ajax.reload();
        notyfToast('Vehicle owner deleted successfully ', 'success')
    })
    .catch(function (error) {
        notyfToast(error.response.data.message, 'error');
    });
}

function showCrudButtons(){
    @can('show vehicle owner')
        $("a[id^=vehicle_owner_show").show();
    @endcan
    @can('edit vehicle owner')
        $("a[id^=vehicle_owner_edit").show();
    @endcan
    @can('destroy vehicle owner')
        $("button[id^=vehicle_owner_destroy").show();
    @endcan
}

</script>